In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import os
os.getcwd()

'C:\\Users\\kazus\\Downloads\\Project_Data\\matplotlib-practice\\mini_projects\\practice_03_Timor-Leste\\src'

In [59]:
df_raw = pd.read_csv(
    "../data/raw_data/pivot.csv",
    header=None
)

In [60]:
df_raw.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,NaN,NaN,NaN,Year,Flow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2021,NaN,NaN,2022,NaN,NaN,2023,NaN,NaN,2024,NaN,NaN,2025,NaN,NaN
2,Reporter,Partner,Commodity,NaN,Export,Import,NaN,Export,Import,NaN,Export,Import,NaN,Export,Import,NaN,Export,Import
3,Timor Leste,WORLD [99],[01] Animals; live,269 363,NaN,269 363,432 935,NaN,432 935,717 287,NaN,717 287,280 140,863,279 278,194 864,NaN,194 864
4,NaN,NaN,[02] Meat and edible meat offal,24 828 197,NaN,24 828 197,32 682 945,NaN,32 682 945,27 937 145,19 336,27 917 809,28 129 369,NaN,28 129 369,29 584 836,NaN,29 584 836

In [61]:
df_raw.iloc[:4, :12]

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,NaN,Year,Flow,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2021,NaN,NaN,2022,NaN,NaN,2023,NaN,NaN
2,Reporter,Partner,Commodity,NaN,Export,Import,NaN,Export,Import,NaN,Export,Import
3,Timor Leste,WORLD [99],[01] Animals; live,269 363,NaN,269 363,432 935,NaN,432 935,717 287,NaN,717 287

In [62]:
df_raw.isna().sum()

0     97
1     97
2      2
3      1
4     32
5      2
6      2
7     46
8      2
9      2
10    25
11     2
12     3
13    32
14     3
15     3
16    29
17     3
dtype: int64

In [63]:
df_cleaned = df_raw.drop(
    columns=[0, 1]
)

In [64]:
df_cleaned.head()

,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,NaN,Year,Flow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2021,NaN,NaN,2022,NaN,NaN,2023,NaN,NaN,2024,NaN,NaN,2025,NaN,NaN
2,Commodity,NaN,Export,Import,NaN,Export,Import,NaN,Export,Import,NaN,Export,Import,NaN,Export,Import
3,[01] Animals; live,269 363,NaN,269 363,432 935,NaN,432 935,717 287,NaN,717 287,280 140,863,279 278,194 864,NaN,194 864
4,[02] Meat and edible meat offal,24 828 197,NaN,24 828 197,32 682 945,NaN,32 682 945,27 937 145,19 336,27 917 809,28 129 369,NaN,28 129 369,29 584 836,NaN,29 584 836

In [65]:
df_imports = df_cleaned.loc[
    3:,
    [2, 5, 8, 11, 14, 17]
]

df_imports.head()

,2,5,8,11,14,17
3,[01] Animals; live,269 363,432 935,717 287,279 278,194 864
4,[02] Meat and edible meat offal,24 828 197,32 682 945,27 917 809,28 129 369,29 584 836
5,"[03] Fish and crustaceans, molluscs and other ...",2 768 025,4 841 524,5 090 998,6 533 920,6 117 497
6,[04] Dairy produce; birds' eggs; natural honey...,7 174 669,6 733 925,8 648 533,9 388 673,9 682 791
7,[05] Animal originated products; not elsewhere...,62 133,45 911,128 906,29 493,NaN

In [66]:
df_imports.columns

Index([2, 5, 8, 11, 14, 17], dtype='int64')

In [67]:
df_imports.rename(
    columns={2: "Commodity",
            5: 2021,
            8: 2022,
            11: 2023,
            14: 2024,
            17: 2025
            },
    inplace=True
)

In [68]:
df_imports

,Commodity,2021,2022,2023,2024,2025
3,[01] Animals; live,269 363,432 935,717 287,279 278,194 864
4,[02] Meat and edible meat offal,24 828 197,32 682 945,27 917 809,28 129 369,29 584 836
5,"[03] Fish and crustaceans, molluscs and other ...",2 768 025,4 841 524,5 090 998,6 533 920,6 117 497
6,[04] Dairy produce; birds' eggs; natural honey...,7 174 669,6 733 925,8 648 533,9 388 673,9 682 791
7,[05] Animal originated products; not elsewhere...,62 133,45 911,128 906,29 493,NaN
...,...,...,...,...,...,...
94,[93] Arms and ammunition; parts and accessorie...,4 691 807,1 178 813,469 168,4 508 676,29 535
95,"[94] Furniture; bedding, mattresses, mattress ...",11 865 116,15 660 306,20 485 942,21 625 877,21 045 989
96,"[95] Toys, games and sports requisites; parts ...",3 159 656,2 167 338,1 961 840,2 063 738,2 214 178
97,[96] Miscellaneous manufactured articles,6 605 565,5 698 168,6 389 833,6 731 316,6 484 810
98,[97] Works of art; collectors' pieces and anti...,31 345,38 496,42 941,62 656,93 556

In [69]:
df_imports.dtypes

Commodity    str
2021         str
2022         str
2023         str
2024         str
2025         str
dtype: object

In [70]:
df_imports.isna().sum()

Commodity    0
2021         0
2022         0
2023         0
2024         1
2025         1
dtype: int64

In [71]:
years = [2021, 2022, 2023, 2024, 2025]
for year in years:
    df_imports[year] = df_imports[year].str.replace(" ", "")

In [72]:
df_imports

,Commodity,2021,2022,2023,2024,2025
3,[01] Animals; live,269363,432935,717287,279278,194864
4,[02] Meat and edible meat offal,24828197,32682945,27917809,28129369,29584836
5,"[03] Fish and crustaceans, molluscs and other ...",2768025,4841524,5090998,6533920,6117497
6,[04] Dairy produce; birds' eggs; natural honey...,7174669,6733925,8648533,9388673,9682791
7,[05] Animal originated products; not elsewhere...,62133,45911,128906,29493,NaN
...,...,...,...,...,...,...
94,[93] Arms and ammunition; parts and accessorie...,4691807,1178813,469168,4508676,29535
95,"[94] Furniture; bedding, mattresses, mattress ...",11865116,15660306,20485942,21625877,21045989
96,"[95] Toys, games and sports requisites; parts ...",3159656,2167338,1961840,2063738,2214178
97,[96] Miscellaneous manufactured articles,6605565,5698168,6389833,6731316,6484810
98,[97] Works of art; collectors' pieces and anti...,31345,38496,42941,62656,93556

In [73]:
for year in years:
    df_imports[year] = pd.to_numeric(
        df_imports[year],
        errors="coerce"
    )

In [74]:
df_imports

,Commodity,2021,2022,2023,2024,2025
3,[01] Animals; live,269363,432935,717287,279278.0,194864.0
4,[02] Meat and edible meat offal,24828197,32682945,27917809,28129369.0,29584836.0
5,"[03] Fish and crustaceans, molluscs and other ...",2768025,4841524,5090998,6533920.0,6117497.0
6,[04] Dairy produce; birds' eggs; natural honey...,7174669,6733925,8648533,9388673.0,9682791.0
7,[05] Animal originated products; not elsewhere...,62133,45911,128906,29493.0,NaN
...,...,...,...,...,...,...
94,[93] Arms and ammunition; parts and accessorie...,4691807,1178813,469168,4508676.0,29535.0
95,"[94] Furniture; bedding, mattresses, mattress ...",11865116,15660306,20485942,21625877.0,21045989.0
96,"[95] Toys, games and sports requisites; parts ...",3159656,2167338,1961840,2063738.0,2214178.0
97,[96] Miscellaneous manufactured articles,6605565,5698168,6389833,6731316.0,6484810.0
98,[97] Works of art; collectors' pieces and anti...,31345,38496,42941,62656.0,93556.0

In [75]:
df_imports.isna().sum()

Commodity    0
2021         0
2022         0
2023         0
2024         1
2025         1
dtype: int64

In [76]:
missing_rows = df_imports[
    df_imports[[2024, 2025]].isna().any(axis=1)
]

missing_rows

,Commodity,2021,2022,2023,2024,2025
7,[05] Animal originated products; not elsewhere...,62133,45911,128906,29493.0,NaN
16,[14] Vegetable plaiting materials; vegetable p...,6648,7005,49,NaN,363.0

In [77]:
df_imports

,Commodity,2021,2022,2023,2024,2025
3,[01] Animals; live,269363,432935,717287,279278.0,194864.0
4,[02] Meat and edible meat offal,24828197,32682945,27917809,28129369.0,29584836.0
5,"[03] Fish and crustaceans, molluscs and other ...",2768025,4841524,5090998,6533920.0,6117497.0
6,[04] Dairy produce; birds' eggs; natural honey...,7174669,6733925,8648533,9388673.0,9682791.0
7,[05] Animal originated products; not elsewhere...,62133,45911,128906,29493.0,NaN
...,...,...,...,...,...,...
94,[93] Arms and ammunition; parts and accessorie...,4691807,1178813,469168,4508676.0,29535.0
95,"[94] Furniture; bedding, mattresses, mattress ...",11865116,15660306,20485942,21625877.0,21045989.0
96,"[95] Toys, games and sports requisites; parts ...",3159656,2167338,1961840,2063738.0,2214178.0
97,[96] Miscellaneous manufactured articles,6605565,5698168,6389833,6731316.0,6484810.0
98,[97] Works of art; collectors' pieces and anti...,31345,38496,42941,62656.0,93556.0

In [78]:
df_imports = df_imports.melt(
    id_vars="Commodity",
    var_name="year",
    value_name="import_value"
)

In [ ]:
# Preserve original commodity names
df_imports["Commodity_Original"] = df_imports["Commodity"].copy()

df_imports["HS_Code"] = (
    df_imports["Commodity"]
    .str.extract(r"\[(\d{2})\]")
)


hs_names = {
    # 01–05: Animal products
    "01": "Live animals",
    "02": "Meat products",
    "03": "Fish and seafood",
    "04": "Dairy, eggs and honey",
    "05": "Other animal products",

    # 06–14: Vegetable products
    "06": "Live plants and flowers",
    "07": "Vegetables",
    "08": "Fruits and nuts",
    "09": "Coffee, tea and spices",
    "10": "Cereals",
    "11": "Milling products",
    "12": "Oil seeds and plants",
    "13": "Gums and resins",
    "14": "Vegetable plaiting materials",

    # 15: Fats and oils
    "15": "Animal and vegetable oils",

    # 16–24: Food, beverages and tobacco
    "16": "Prepared meat and seafood",
    "17": "Sugar and confectionery",
    "18": "Cocoa products",
    "19": "Prepared cereal products",
    "20": "Prepared fruits and vegetables",
    "21": "Other food preparations",
    "22": "Beverages and spirits",
    "23": "Food industry residues",
    "24": "Tobacco products",

    # 25–27: Mineral products
    "25": "Salt, stone and minerals",
    "26": "Ores, slag and ash",
    "27": "Mineral fuels and oils",

    # 28–38: Chemicals
    "28": "Inorganic chemicals",
    "29": "Organic chemicals",
    "30": "Pharmaceuticals",
    "31": "Fertilizers",
    "32": "Dyes and pigments",
    "33": "Perfumes and cosmetics",
    "34": "Soaps and detergents",
    "35": "Starches and proteins",
    "36": "Explosives and pyrotechnics",
    "37": "Photographic goods",
    "38": "Other chemical products",

    # 39–40: Plastics and rubber
    "39": "Plastics",
    "40": "Rubber products",

    # 41–43: Hides and leather
    "41": "Raw hides and skins",
    "42": "Leather goods",
    "43": "Furs and artificial fur",

    # 44–46: Wood and related products
    "44": "Wood products",
    "45": "Cork products",
    "46": "Straw and plaiting products",

    # 47–49: Paper and printing
    "47": "Wood pulp",
    "48": "Paper and paperboard",
    "49": "Printed materials",

    # 50–63: Textiles
    "50": "Silk",
    "51": "Wool and animal hair",
    "52": "Cotton",
    "53": "Other vegetable fibres",
    "54": "Synthetic filaments",
    "55": "Synthetic staple fibres",
    "56": "Wadding and nonwovens",
    "57": "Carpets",
    "58": "Special woven fabrics",
    "59": "Coated textile fabrics",
    "60": "Knitted fabrics",
    "61": "Knitted clothing",
    "62": "Non-knitted clothing",
    "63": "Other textile articles",

    # 64–67: Footwear and accessories
    "64": "Footwear",
    "65": "Headwear",
    "66": "Umbrellas and walking sticks",
    "67": "Feathers and artificial flowers",

    # 68–70: Stone, ceramics and glass
    "68": "Stone and cement products",
    "69": "Ceramics",
    "70": "Glass products",

    # 71: Precious materials
    "71": "Jewellery and precious stones",

    # 72–83: Metals
    "72": "Iron and steel",
    "73": "Iron or steel articles",
    "74": "Copper products",
    "75": "Nickel products",
    "76": "Aluminium products",
    # HS77 is reserved and absent from this dataset
    "78": "Lead products",
    "79": "Zinc products",
    "80": "Tin products",
    "81": "Other base metals",
    "82": "Metal tools and cutlery",
    "83": "Miscellaneous metal articles",

    # 84–85: Machinery and electrical equipment
    "84": "Machinery",
    "85": "Electrical machinery",

    # 86–89: Transport equipment
    "86": "Railway equipment",
    "87": "Vehicles",
    "88": "Aircraft and spacecraft",
    "89": "Ships and boats",

    # 90–92: Precision instruments
    "90": "Optical and medical instruments",
    "91": "Clocks and watches",
    "92": "Musical instruments",

    # 93–97: Other manufactured goods
    "93": "Arms and ammunition",
    "94": "Furniture and bedding",
    "95": "Toys, games and sports goods",
    "96": "Miscellaneous manufactured goods",
    "97": "Art and antiques"
}

# Replace long names with short names
df_imports["Commodity"] = (
    df_imports["HS_Code"].map(hs_names)
)

df_imports["import_million"] = (df_imports["import_value"] / 1000000).round(5)

df_imports

In [ ]:
fig, ax = plt.subplots(
    2,
    3,
    facecolor="white",
    figsize=(18, 10)
)

In [ ]:
years = [2021, 2022, 2023, 2024, 2025]
axes = ax.ravel()

for i, year in enumerate(years):
    df_year = df_imports[df_imports["year"] == year]
    df_top10 = df_year.nlargest(10, "import_value")

    axes[i].barh(
        df_top10["Commodity"],
        df_top10["import_million"]
    )

    axes[i].set_xlabel("Commodity")
    axes[i].set_ylabel("import value (million USD)")
    axes[i].set_title(f"Top 10 Imported Commodities in Timor-Leste, {year}")
    axes[i].grid()

In [ ]:
import matplotlib.pyplot as plt

years = [2021, 2022, 2023, 2024, 2025]

# Create a 2 × 3 subplot grid
fig, ax = plt.subplots(
    2, 3,
    figsize=(18, 10),
    facecolor="white"
)

axes = ax.ravel()

for i, year in enumerate(years):

    # Filter data by year
    df_year = df_imports[df_imports["year"] == year]

    # Select top 10 commodities
    df_top10 = df_year.nlargest(10, "import_value")

    # Create horizontal bar chart
    axes[i].barh(
        df_top10["Commodity"],
        df_top10["import_million"]
    )

    # Improve readability
    axes[i].invert_yaxis()
    axes[i].set_xlabel("Import Value (Million USD)")
    axes[i].set_title(f"Top 10 Imports ({year})")
    axes[i].grid(axis="x", alpha=0.3)

# Hide unused subplot
axes[5].set_visible(False)

plt.tight_layout()
plt.show()
plt.savefig(
    "../output/top10_imports_2021_2025.png"
)